[application]
	dependencies = [
		"../../bower_components/angular-sanitize/angular-sanitize.js",
		"../../bower_components/angular-bootstrap/ui-bootstrap.js",
		"../../bower_components/angular-ui-select/dist/select.js",
	]