[application]
	dependencies = [
		"../../bower_components/lodash/dist/lodash.underscore.js",
		"../../bower_components/angular/angular.js",
		"../../bower_components/angular-translate/angular-translate.js",
		"../../bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.js",
		"../../bower_components/angular-ui-router/release/angular-ui-router.js",
		"../../bower_components/angular-bootstrap/ui-bootstrap.js",
		"../../bower_components/angular-sanitize/angular-sanitize.js",
		"../../bower_components/angular-ui-select/dist/select.js",
		"../../bower_components/lavaboom/dist/lavaboom-angular.js",
		"../../bower_components/lavaboom/dist/lavaboom-api.js",
		"../../bower_components/angular-base64/angular-base64.js",
		"../../bower_components/ng-tags-input/ng-tags-input.js",
		"../../vendor/openpgp.js"
	]