[application]
	dependencies = [
		"../../bower_components/angular-sanitize/angular-sanitize.js",
		"../../bower_components/angular-bootstrap/ui-bootstrap.js",
		"../../bower_components/angular-ui-select/dist/select.js",
				'../../bower_components/rangy/rangy-core.js',
		'../../bower_components/rangy/rangy-selectionsaverestore.js',
		'../../bower_components/textAngular/dist/textAngular-sanitize.min.js',
		'../../bower_components/textAngular/dist/textAngular.min.js'
	]