[application]
	dependencies = [
		"../../bower_components/angular/angular.js",
		"../../bower_components/angular-translate/angular-translate.js",
		"../../bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.js"
	]