[application]
	dependencies = [
		'../../bower_components/angular/angular.js',
        '../../bower_components/angular-translate/angular-translate.js',
        '../../bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.js',

		'../../bower_components/angular-validation-match/dist/angular-input-match.js',
		'../../bower_components/angular-ui-router/release/angular-ui-router.js',

		'../../bower_components/lavaboom/dist/lavaboom-angular.js',
		'../../bower_components/file-saver/FileSaver.js',
		'../../bower_components/angular-co/dist/co.js',

		#'../../bower_components/sockjs-client/dist/sockjs.js',
	]
