[application]
	dependencies = [
		"../../bower_components/lodash/dist/lodash.underscore.js",

		"../../bower_components/angular-sanitize/angular-sanitize.js",
		"../../bower_components/angular-validation-match/dist/angular-input-match.js",
		"../../bower_components/angular-ui-router/release/angular-ui-router.js",

		"../../bower_components/lavaboom/dist/lavaboom-angular.js",
		"../../bower_components/lavaboom/dist/lavaboom-api.js",
		"../../bower_components/file-saver/FileSaver.js",
		"../../vendor/openpgp.js",
		#"../../bower_components/sockjs-client/dist/sockjs.js",
	]