[application]
	dependencies = [
		"../../../node_modules/6to5/browser-polyfill.js",
		"../../bower_components/lodash/lodash.js",
		"../../bower_components/lavaboom/dist/lavaboom-api.js",
		"../../../node_modules/setimmediate/setImmediate.js"
	]