image: registry.lavaboom.io/lavaboom/wrapper-web
script:
  - npm install -g gulp
  - npm install
  - gulp develop
  - "if [ \"$DRONE_BRANCH\" = \"master\" ]; then export CONTAINER_NAME=web-master; export CONTAINER_PORT=10000; fi"
  - "if [ \"$DRONE_BRANCH\" = \"staging\" ]; then export CONTAINER_NAME=web-staging; export CONTAINER_PORT=10001; fi"
  - "if [ \"$DRONE_BRANCH\" = \"develop\" ]; then export CONTAINER_NAME=web-develop; export CONTAINER_PORT=10002; fi"
  - "if [ -n \"$CONTAINER_NAME\" ]; then chmod +x ./.drone/build.sh && ./.drone/build.sh; fi"
  - "if [ -n \"$CONTAINER_NAME\" ]; then ssh -p 36412 root@lisa.lavaboom.io \"/opt/deploy/$CONTAINER_NAME.sh\"; fi"
notify:
  slack:
   - webhook_url: $$SLACK_URL
   - channel: $$SLACK_CHANNEL
   - username: lavadrone
   - on_started: true
   - on_success: true
   - on_failure: true