image: registry.lavaboom.io/lavaboom/wrapper-web
script:
  - pip install fabric
  - npm install -g gulp
  - npm install
  - "if [ \"$DRONE_BRANCH\" = \"master\" ]; export API_URI=\"https://api.lavaboom.com\"; fi"
  - "if [ \"$DRONE_BRANCH\" = \"staging\" ]; export API_URI=\"https://api.lavaboom.io\"; fi"
  - "if [ \"$DRONE_BRANCH\" = \"develop\" ]; export API_URI=\"https://api.lavaboom.co\"; fi"
  - gulp develop
  - "if [ \"$DRONE_BRANCH\" = \"master\" ]; then fab -H marge.lavaboom.io:36104 deploy; fi"
  - "if [ \"$DRONE_BRANCH\" = \"staging\" ]; then fab -H lisa.lavaboom.io:36412 deploy; fi"
  - "if [ \"$DRONE_BRANCH\" = \"develop\" ]; then fab -H bart.lavaboom.io:36467 deploy; fi"
notify:
  slack:
   - webhook_url: $$SLACK_URL
   - channel: $$SLACK_CHANNEL
   - username: lavadrone
   - on_started: true
   - on_success: true
   - on_failure: true