image: registry.lavaboom.io/lavaboom/wrapper-web
script:
  - pip install fabric
  - fab integrate
notify:
  slack:
   webhook_url: $$SLACK_URL
   channel: $$SLACK_CHANNEL
   username: lavadrone
   on_started: true
   on_success: true
   on_failure: true
