[MANIFEST]
	version = "1.0"

[APPLICATION]
	name = "LavaMail"
	version = "1.0"
	description = "Lava Mail application"
	type = "angular"

	moduleName = "LavaMail"

	dependencies = [
		"LavaUtils",
		"lavaboom.api",
		"ui.router",
		"ui.bootstrap",
		"ui.select",
		"pascalprecht.translate",
		"infinite-scroll",
		"angular-co",
		"ngAutodisable",
		"cfp.hotkeys",
		"yaru22.angular-timeago",
		"dialogs.main",
		"ngMessages",
		"froala"
	]

	productionOnlyDependencies = [
	]

	vendorDependencies = [
		"bower@FroalaWysiwygEditor/js/froala_editor.min.js",
		"bower@FroalaWysiwygEditor/js/plugins/tables.min.js",
		"bower@FroalaWysiwygEditor/js/plugins/urls.min.js",
		"bower@FroalaWysiwygEditor/js/plugins/lists.min.js",
		"bower@FroalaWysiwygEditor/js/plugins/colors.min.js",
		"bower@FroalaWysiwygEditor/js/plugins/font_family.min.js",
		"bower@FroalaWysiwygEditor/js/plugins/font_size.min.js",
		"bower@FroalaWysiwygEditor/js/plugins/block_styles.min.js",
		"bower@FroalaWysiwygEditor/js/plugins/media_manager.min.js",
		"bower@FroalaWysiwygEditor/js/plugins/video.min.js",
		"bower@FroalaWysiwygEditor/js/plugins/char_counter.min.js",
		"bower@FroalaWysiwygEditor/js/plugins/entities.min.js",
		"bower@FroalaWysiwygEditor/js/langs/en_us.js",
		"bower@angular-froala/src/angular-froala.js",

		"bower@angular-bootstrap/ui-bootstrap.js",
		"bower@angular-bootstrap/ui-bootstrap-tpls.js",
		"bower@angular-ui-select/dist/select.js",

		"bower@ngInfiniteScroll/build/ng-infinite-scroll.js",
		"bower@angular-hotkeys/build/hotkeys.js",
		"bower@angular-timeago/src/timeAgo.js",
		"bower@angular-dialog-service/dist/dialogs.min.js",
		"npm@q-encoding/q.js",
	]