[MANIFEST]
	version = "1.0"

[APPLICATION]
	name = "LavaMail"
	version = "1.0"
	description = "Lava Mail application"
	type = "angular"

	moduleName = "LavaMail"

	dependencies = [
		"LavaUtils",
		"lavaboom.api",
		"ngSanitize",
		"ui.router",
		"ui.bootstrap",
		"ui.select",
		"textAngular",
		"pascalprecht.translate",
		"infinite-scroll",
		"angular-co",
		"ngAutodisable",
		"cfp.hotkeys",
		"yaru22.angular-timeago",
		"dialogs.main",
		"ngMessages"
	]

	productionOnlyDependencies = [
		"templates"
	]
    	
	vendorDependencies = [
		"../../bower_components/angular-bootstrap/ui-bootstrap.js",
		"../../bower_components/angular-bootstrap/ui-bootstrap-tpls.js",
		"../../bower_components/angular-ui-select/dist/select.js",
		"../../bower_components/textAngular/dist/textAngular-rangy.min.js",
        "../../bower_components/textAngular/dist/textAngular.min.js",
        "../../bower_components/ngInfiniteScroll/build/ng-infinite-scroll.js",
        "../../bower_components/angular-hotkeys/build/hotkeys.js",
        "../../bower_components/angular-timeago/src/timeAgo.js",
        "../../bower_components/angular-dialog-service/dist/dialogs.min.js"
	]